steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/scout-api', './api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/scout-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'scout-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/scout-api'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--set-secrets'
      - 'GENAI_API_KEY=GENAI_API_KEY:latest,MAPS_API_KEY=MAPS_API_KEY:latest'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/scout-api'